### ISSUE TITLE
Not (yet) supported in zigbee2mqtt 

### ISSUE THREAD

**Issue by Ctrl-F4** [devbis/z03mmc#1]
Great project!  Just successfully flashed this firmware and paired it with zigbee2mqtt. Would be nice if it will be supported by zigbee2mqtt in the future. Is there already an external converter available?

![LYWSD03MMC](https://github.com/devbis/z03mmc/assets/48384485/29079b3d-2841-404c-a644-3352965bc732)

**Comment by devbis** [comment]
Yes, it is not in the repo, but I'll add it soon. 

```js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const ota = require('zigbee-herdsman-converters/lib/ota');
const e = exposes.presets;

const definition = {
    zigbeeModel: ['LYWSD03MMC'],
    model: 'LYWSD03MMC',
    vendor: 'Xiaomi',
    description: 'Temperature & humidity sensor',
    fromZigbee: [fz.temperature, fz.humidity, fz.battery],
    toZigbee: [],
    meta: {battery: {voltageToPercentage: '3V_2500'}},
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        const bindClusters = ['msTemperatureMeasurement', 'msRelativeHumidity', 'genPowerCfg'];
        await reporting.bind(endpoint, coordinatorEndpoint, bindClusters);
        await reporting.temperature(endpoint);
        await reporting.humidity(endpoint);
        await reporting.batteryVoltage(endpoint);
    },
    exposes: [e.temperature(), e.humidity(), e.battery()],
  
    ota: ota.zigbeeOTA,
};

module.exports = definition;
```

**Comment by Ctrl-F4** [comment]
Thank you for the converter, it is now recognized in zigbee2mqtt although humidity value seems not (yet) reported? 

![z03mmc](https://github.com/devbis/z03mmc/assets/48384485/3bc1fa4a-3fd7-4b7b-a79a-fd948a17a76a)


I also checked with the z03mmc_heiman firmware and is also not reporting the humidity value?

![z03mmc_heiman](https://github.com/devbis/z03mmc/assets/48384485/965174be-8207-41ab-9da5-adf33600d1d1)

**Comment by devbis** [comment]
Both values are reported. Check temp and humid clusters are bound in zigbee2mqtt tab. And rebind if checkboxes are different

<img width="1591" alt="Screenshot 2023-10-08 at 22 18 03" src="https://github.com/devbis/z03mmc/assets/12081127/e3fbc7e8-fc95-49c2-81b8-577600e751d2">

**Comment by Ctrl-F4** [comment]
Checkboxes are same as yours. Tried to rebind, rejoin, reflash but no humidity readings. Downloaded your precompiled fw and no change . Tried to sniff the data with wireshark but found no data for humidity.     
Don't know how to debug further.

![Wireshark](https://github.com/devbis/z03mmc/assets/48384485/b558d43a-1e3d-4090-950c-31522d360c99)

**Comment by devbis** [comment]
Can you read values out of the cluster with dev console in zigbee2mqtt for a device?
<img width="1379" alt="Screenshot 2023-10-09 at 11 24 16" src="https://github.com/devbis/z03mmc/assets/12081127/e5f77c88-f40f-4c2f-ba99-949ccd32394c">

**Comment by devbis** [comment]
Please, check firmware from this run: https://github.com/devbis/z03mmc/actions/runs/6455005642
It has increased number of items for reporting and binding and it could help.

**Comment by Ctrl-F4** [comment]
> Can you read values from the cluster with dev console in zigbee2mqtt for a device? <img alt="Screenshot 2023-10-09 at 11 24 16" width="1379" src="https://user-images.githubusercontent.com/12081127/273518857-e5f77c88-f40f-4c2f-ba99-949ccd32394c.png">

Yes this works! But value not updated automatic.  Not yet tried the test fw (6455005642)

**Comment by Ctrl-F4** [comment]
> Please, check firmware from this run: https://github.com/devbis/z03mmc/actions/runs/6455005642 It has increased number of items for reporting and binding and it could help.

Same behaviour for this fw ( uploaded z03mmc.bin). Via dev console forcing humidity readout, it shows same value as lcd. Then increase temp and humidity at the same time only temp reading is updated.

**Comment by devbis** [comment]
What's on the reporting page? Is humidity configured? Does remove and and set back change anything?

**Comment by devbis** [comment]
I have the same parameters and it seems reporting well (though I'm not 100% sure). I'm testing on zigbee2mqtt 1.33

**Comment by Ctrl-F4** [comment]
Read result of 'genBasic': {"hwVersion":14}
zigbee2mqtt 1.33.1-dev commit: [2aae1bd5](https://github.com/Koenkk/zigbee2mqtt/commit/2aae1bd5)
zStack3x0 Coordinator revision 20230507 (CC2652P Sonoff  ZBDongle-P)

If you need more information let me know, ready to test.
(In the meantime i have to find out how to set up OTA for convenience)

**Comment by devbis** [comment]
Can you please try the latest pre-release? It is build with updated SDK and may fix reporting issues.

**Comment by Ctrl-F4** [comment]
Yes it started reporting humidity with this new fw! 
I'm curious how long battery will last in comparison with the ble fw. (when configured same reporting interval) 
Thanks again!

**Comment by devbis** [comment]
I don't have long-lasting results with a battery, but the expected working time should be approximately the same as with bluetooth firmware.
