### ISSUE TITLE
Датчики отваливаются

### ISSUE THREAD

**Issue by booroondook-eng** [devbis/z03mmc#10]
У меня два перепрошитых датчика (был еще третий, но я его вернул на BLE).
Выясняется, что через несколько часов работы (точно не скажу - несколько часов, но не более суток) оба датчика "отваливаются" от Zigbee2MQTT. В списке устройств напротив них высвечивается красная надпись "Оффлайн".
Помогает передергивание батарейки, но с учетом конструктивных особенностей корпусов этих датчиков, да еще приклеенных на стену, передергивание батарейки превращается в сложную задачу.
Что можно предпринять, чтобы не было отвалов?

**Comment by Sergey-SRG** [comment]
> У меня два перепрошитых датчика (был еще третий, но я его вернул на BLE). Выясняется, что через несколько часов работы (точно не скажу - несколько часов, но не более суток) оба датчика "отваливаются" от Zigbee2MQTT. В списке устройств напротив них высвечивается красная надпись "Оффлайн". Помогает передергивание батарейки, но с учетом конструктивных особенностей корпусов этих датчиков, да еще приклеенных на стену, передергивание батарейки превращается в сложную задачу. Что можно предпринять, чтобы не было отвалов?

А что на счёт качества связи у вас? Какие показатели lqi?

**Comment by SoulOnFire** [comment]
I had a power failure, all the routers and coordinators were turned off, and then only by removing the battery did they reconnect to the Z2M.

**Comment by booroondook-eng** [comment]
> 
> А что на счёт качества связи у вас? Какие показатели lqi?
145 - 155

**Comment by franciscofsales** [comment]
> I had a power failure, all the routers and coordinators were turned off, and then only by removing the battery did they reconnect to the Z2M.

I've had the same issue

**Comment by IvanGavrilenko** [comment]
То же самое

**Comment by igelbro** [comment]
Та же беда

**Comment by malehovich** [comment]
+
lqi 87

**Comment by Ccrrocus** [comment]
![LQI and Batt lywsd03mmc to Zigbee](https://github.com/devbis/z03mmc/assets/132225510/8355dc22-873c-437d-bcf4-03c7fa2fd5bd)

**Comment by lardeg** [comment]
Тоже самое. из 5 датчиков 3 стабильно отваливаются в течении суток.

**Comment by booroondook-eng** [comment]
Отвалы продолжаются - новая версия прошивки не помогла.

**Comment by seregahere** [comment]
HA, Zigbee2MQTT
Прошивка 1.0.2

Днем было отключение электричества на несколько часов. После восстановления все 5 датчиков отвалились, по прошествии 2+ часов ни один не ожил. Попытки в Zigbee2MQTT из консоли разработчика считать какой-то атрибут (например кластер genBasic, атрибут manufacturerName) приводят к ошибке

> 2023-10-26 17:59:32Publish 'set' 'read' to 'temperature_guestroom' failed: 'Error: Read 0xa4c138f58fbd37ac/1 genBasic(["manufacturerName"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 48889 - 1 - 35 - 0 - 1 after 10000ms)'

lqi, как и другие данные, не обновляются с момента отключения электричества.

**Comment by Mostalk** [comment]
На 1.0.4 до сих пор есть эта проблема

**Comment by Ccrrocus** [comment]
![LQI and Batt lywsd03mmc to Zigbee 3](https://github.com/devbis/z03mmc/assets/132225510/e54de85e-044c-4e70-b755-7502a6fc07d1)

**Comment by Mostalk** [comment]
Просто так отвала нет, он происходит при потере связи, в любом виде. Будь то перезагрузка роутера или отдаление датчика.

**Comment by Ccrrocus** [comment]
Пару раз обновлялась система с перезагрузкой, один раз выключал не надолго, вроде все норм с датчиком, менял параметры и он сразу подхватывал.

**Comment by IvanGavrilenko** [comment]
![IMG_20231027_205953](https://github.com/devbis/z03mmc/assets/37136246/49544d99-ed3d-43b6-a8fa-33ec814659c9)

Прошивка 1.0.4 - датчик стоит на одном месте,  НА не перезагружался - около 17.00 передал последние показания и сказал до свидания

**Comment by Mostalk** [comment]
> Пару раз обновлялась система с перезагрузкой, один раз выключал не надолго, вроде все норм с датчиком, менял параметры и он сразу подхватывал.

Может тоже от HW зависит, но у меня два, как я понял, разных HW на датчиках. Но ситуация одинаковая. Перезагрузка HA, либо потеря сигнала - все. Нужно передёргивать батарейку

**Comment by kirush0280** [comment]
Проблему подтверждаю на версии 3001-1002, если отключить электричество на шлюзе минут на 10, больше они не переподключаются.
Также могут зависнуть в процессе работы - помогает только батарейка.
Сейчас обновляется ан 3001-1004, там поменяли, как я понял только периоды опроса. Наблюдаем дальше.

**Comment by devbis** [comment]
> Просто так отвала нет, он происходит при потере связи, в любом виде. Будь то перезагрузка роутера или отдаление датчика.

Спасибо за идею, да, у меня тоже воспроизводится. Буду копать как это решить.

**Comment by komw** [comment]
How do you add it to the z2m? Mine says that its not supported

**Comment by fryc88** [comment]
You need to add custom converter for it. It is mentioned and converter file is added, however mine gives me error regarding temperature value something

**Comment by devbis** [comment]
@Mostalk @IvanGavrilenko @booroondook-eng  Can you please check out this firmware? it has some improvements regarding reconnecting but I want to double check it works with your issues


[fw.zip](https://github.com/devbis/z03mmc/files/13195682/fw.zip)

**Comment by booroondook-eng** [comment]
> @booroondook-eng Can you please check out this firmware? 
> 
With firmware 1.0.3/1.0.4 disconnect problems disappeared, so I don't see the need to test the release you propose.
Thank you for your responsiveness!

**Comment by Mostalk** [comment]
> [fw.zip](https://github.com/devbis/z03mmc/files/13195682/fw.zip)

I turned off the zigbee stick for a few minutes, everything seemed to be fine, the connection was restored. I'll keep an eye on it and do a couple of tests.

**Comment by IvanGavrilenko** [comment]
> @Mostalk @IvanGavrilenko @booroondook-eng Can you please check out this firmware? it has some improvements regarding reconnecting but I want to double check it works with your issues
> 
> [fw.zip](https://github.com/devbis/z03mmc/files/13195682/fw.zip)

Situation has PARTLY improved - now I've obtained data for about 8 hours (instead of about 1-2)

![Screenshot_2023-10-29-09-23-31-48_c3a231c25ed346e59462e84656a70e50](https://github.com/devbis/z03mmc/assets/37136246/7b3e7fc9-4bf0-47a3-ba1a-8c0b7f6b5e90)

But finally the sensor again stopped sending values (about 7.00 at the screenshot)

**Comment by Alex500317** [comment]
> 
> [fw.zip](https://github.com/devbis/z03mmc/files/13195682/fw.zip)

I also tried this version. The sensors began to reconnect to the gateway after it was lost! This is very good! Thank you!

**Comment by devbis** [comment]
@IvanGavrilenko 
> But finally the sensor again stopped sending values (about 7.00 at the screenshot)
> 

Did something peculiar happen on 7.00?

**Comment by Mostalk** [comment]
The sensors worked for some time. Now there seem to be no problems on both sensors.

Thank you!

![image](https://github.com/devbis/z03mmc/assets/9198186/745f342f-4529-4a30-bc5f-5b7cb1b6120e)

**Comment by IvanGavrilenko** [comment]
> Did something peculiar happen on 7.00?

No h like previously just in a moment sensor stopped sending data

**Comment by IvanGavrilenko** [comment]
> Did something peculiar happen on 7.00?

Now it seems all Ok - working for about 24h fine. I've flashed to the original firmware and then to the ZigBee via UART

I SUPPOSE the issue was - I've flashed the 

> [fw.zip](https://github.com/devbis/z03mmc/files/13195682/fw.zip)

file with UART, and put ota.zigbee to the ota folder and thus sensor started working as I've flashed it and when ota transfer was finished - at about 7am the sensor stopped sending data.

**Comment by lardeg** [comment]
> @Mostalk @IvanGavrilenko @booroondook-eng Can you please check out this firmware? it has some improvements regarding reconnecting but I want to double check it works with your issues
> 
> [fw.zip](https://github.com/devbis/z03mmc/files/13195682/fw.zip)

Как прошить это прошивку?

**Comment by devbis** [comment]
Fixed reconnecting on network loss in https://github.com/devbis/z03mmc/releases/tag/1.0.5
