### ISSUE TITLE
change version installed?

### ISSUE THREAD

**Issue by carlituxman** [devbis/z03mmc#101]
I have some devices, some has: Firmware: 3001-1006 and others Firmware: 3001-0118

The battery life devices with fw:3001-1006 is is greater than devices with fw:3001-0118

All appear up-to-date binary_sensor.XXXX_update_available 

How can I change the version installed?

**Comment by devbis** [comment]
Hi! fw:3001-0118 is not from this repository, but from a fork project https://github.com/pvvx/ZigbeeTLc/ 

To switch to a different firmware you can:

1. Revert to Bluetooth firmware and than flash any firmware you like
2. Change device ID in zigbee OTA header and use local OTA in z2m/zha to switch between different firmwares
3. Flash firmware over the wires

**Comment by carlituxman** [comment]
How can revert to bluetooth fw??

**Comment by carlituxman** [comment]
Is possible change options same on ble version, like  smiley, comfort?....
