### ISSUE TITLE
battery life very short

### ISSUE THREAD

**Issue by carlituxman** [devbis/z03mmc#102]
The battery life is very short. Is possible change the read sensor period?

**Comment by devbis** [comment]
What firmware version do you use?

**Comment by carlituxman** [comment]
Fw version 3001-0118

How can I revert to bluetooth?

**Comment by devbis** [comment]
It's not a firmware from this project, but from a fork. Please, use right firmware from https://github.com/pvvx/ATC_MiThermometer/tree/master/zigbee_ota and local OTA functionality for z2m or ZHA. Or solder wires if you're using different software.

**Comment by carlituxman** [comment]
I just revert to ble version and then install: fw:3001-1006 but at z2m still appear 3001-0118
I sure installed https://github.com/devbis/z03mmc/releases/tag/1.0.6

**Comment by devbis** [comment]
Z2m caches some data from devices, you can read values from attributes manually via developer console for the device. Or reconfigure (don't know if it helps), or delete the device, restart z2m and pair again. In case of a different tool to control zigbee network there could be different ways to clean the cache

**Comment by pbranly** [comment]
Hi @devbis 
Sorry for my English.
I am a little bit lost with all the versions . I use your version (1.0.6) for my 2 thermometers 
Is your advice to use a firmware from a different GitHub ?
Thanks
Phil

**Comment by devbis** [comment]
No.

**Comment by pbranly** [comment]
> No.

👍
