### ISSUE TITLE
Can not flash OTA the transitional firmware ATC_ota_400000

### ISSUE THREAD

**Issue by christescu** [devbis/z03mmc#108]
When selecting ATC_ota_400000, I get the message 'Size firmware is more 208 kbytes!'
I have custom firmware:
Hardware Revision String: B1.9
Software Revision String: V4.1
Firmware Revision String: github.com/pvvx
Detected custom Firmware
Hardware Version: LYWSD03MMC B1.9, Software Version: 4.1, Sensor: SHT4x
Custom config HEX string: 552d01fdf42804a93131033c000000

Same thing happens if I first flash 'Original_OTA_Xiaomi_LYWSD03MMC_v1.0.0_0130.bin', then I make 'Do Activation'.

Later edit: Flashing directly z03mmc.bin OTA using Telink Flasher works like a charm. I tried with 4 LYWSD03MMC and zigbee2mqtt see the devices immediately. No error afterword.

**Comment by devbis** [comment]
Transitional firmware is just about 80kb. Maybe you have downloaded something different.

**Comment by christescu** [comment]
Right, I take the file with a RPI and yes, it has 81k.
I don't know why windows download it as a 387k file.
