### ISSUE TITLE
new z2m features refused

### ISSUE THREAD

**Issue by pbranly** [devbis/z03mmc#112]
Hi
How is it possible to use the new features that seem available in zigbee2mqtt ? each one is refused as unsupported
Thanks
Philippe
![2024-02-02_08-55](https://github.com/devbis/z03mmc/assets/22018509/e2513845-1a48-449f-a0e7-64b7242e1eb2)

**Comment by polygon242** [comment]
same here
`Publish 'set' 'temperature_calibration' to 'Sensor Temp Xiaomi 05' failed: 'Error: Write 0xa4c1384a104079e6/1 hvacUserInterfaceCfg({"256":{"value":1,"type":40}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'`

**Comment by devbis** [comment]
The convertor is broken by a user. I"m working on it. Probably, a custom convertor from this repo could help.

**Comment by pbranly** [comment]
Hi
Will you make a new release ?
Thanks
Phil

**Comment by VivantSenior** [comment]
> The converter is broken by a user. I"m working on it. Probably, a custom converter from this repo could help.

@devbis thanks for the hint. I was able to use [external converter](https://github.com/devbis/z03mmc/blob/master/converters/lywsd03mmc.js) from your repo. Can't see any errors coming from my instances of [LYWSD03MMC](https://www.zigbee2mqtt.io/devices/LYWSD03MMC.html) and all of the sensors are correctly reporting data.

**Comment by pbranly** [comment]
Hi after several tentatives I could use the external converter 
The result is that all the additional menus in my initial post are now absent 
Is it normal ?
Thanks
Phil

**Comment by devbis** [comment]
The fixed convertor is in [PR](https://github.com/Koenkk/zigbee-herdsman-converters/pull/7015) but may be delayed due to z2m release policy.
It adds new features which were introduced in the latest FW 1.1.0 with backward compatibility. 

Before it it merged to z2m and released, you can use custom convertor from this repo: https://github.com/devbis/z03mmc/blob/master/converters/lywsd03mmc.js

**Comment by pbranly** [comment]
Hi 
I don't have any proposal to update the f/w to 1.1.0.
So with the new converter, the new configuration menus are back but generate a lot of errors ...so don't work
How to force f/w update to 1.1.0 ?
Thanks
Phil

**Comment by devbis** [comment]
New features will be available starting from 1.1.0. To have it in z2m you can either wait for https://github.com/Koenkk/zigbee-OTA/pull/440 merged or use local OTA index https://www.zigbee2mqtt.io/guide/usage/ota_updates.html#local-ota-index-and-firmware-files
