### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by Sakriel** [devbis/z03mmc#128]
Heyy - I wanted to upgrade my xiaomi bluetooth temp/humidity sensor. I reached state where i uploaded the [ATC_ota_40000.bin](https://github.com/devbis/z03mmc/releases/download/1.1.0/ATC_ota_40000.bin) and it worked fine. Now i can modify config etc. The next step should be uploading [z03mmc.bin](https://github.com/devbis/z03mmc/releases/download/1.1.0/z03mmc.bin) BUT! when i click start flashing it hangs on: "Status: Clear Ext.OTA region (129kib)..." Idk what should i do - can you help me please?

**Comment by Sakriel** [comment]
The log is:
6:58:55 PM: Searching for devices
6:59:54 PM: Connecting to: ATC_&&&&&&(hashed)
7:00:04 PM: Hardware Revision String: B1.7
7:00:04 PM: Software Revision String: V9.9
7:00:04 PM: Firmware Revision String: github.com/devbis
7:00:04 PM: Detected custom Firmware
7:00:04 PM: Hardware Version: LYWSD03MMC B1.7, Software Version: 9.9, Sensor: SHT4x
7:00:04 PM: Custom config HEX string: 552d1000002804a9313104b4
7:00:45 PM: File: z03mmc.bin
7:00:45 PM: File size: 131300 bytes
7:00:45 PM: Count: 8207
7:00:50 PM: Start DFU
7:00:51 PM: Clear Ext.OTA region (129kib)...

**Comment by EnTonyH** [comment]
How did you solved it? This happend to me too.

**Comment by Sakriel** [comment]
@EnTonyH - I used different network flasher. That is it. But honestly i dont remember which one worked. i have been trying with everything i could.

**Comment by EnTonyH** [comment]
Thank you for the answer. I tried it once more with version 1.1.0 and ended up stuck at 'Clear Ext.OTA region (129kib)...'. Then, I tried an older version, 1.0.6, and it works fine.

**Comment by pablobirukov** [comment]
> Thank you for the answer. I tried it once more with version 1.1.0 and ended up stuck at 'Clear Ext.OTA region (129kib)...'. Then, I tried an older version, 1.0.6, and it works fine.

Same here
