### ISSUE TITLE
Add support for Ruuvi Tags (bluetooth) ??

### ISSUE THREAD

**Issue by thestraycat** [devbis/z03mmc#133]
The ruuvi tag bluetooth project has been a great bluetooth beacon project for many years... And currently a hardware device is needed to manage these extend their range for optimal support.

Would it be possible to convert these to use the zigbee protocol at all?

https://ruuvi.com/ruuvitag/

**Comment by devbis** [comment]
According to the images, the chip N52832 that is used in ruuvitag doesn't support Zigbee, only BLE
https://www.nordicsemi.com/products/nrf52832

**Comment by thestraycat** [comment]
Thanks for confirming, a bit of a shame... Is the custom firmware not applying an emulated zigbee using the underlying hardware then i take it? So in escense, the only reason the xiaomi temp sensors work is that in the spec sheet they say they also support zigbee??

**Comment by devbis** [comment]
It says that its sibling CPU supports zigbee. But under the hood, all chips are the same. Maybe nordic chips has something similar and lower models support featured from the models above, but it needs to be checked. I think it is not the matter of this project which aims Telink chips.
