### ISSUE TITLE
Wired Values

### ISSUE THREAD

**Issue by agmorpheus** [devbis/z03mmc#148]
After flashing my sensor via this page https://devbis.github.io/telink-zigbee/ and connecting it to zigbee2mqtt, it shows some strange values in z2m.

![image](https://github.com/devbis/z03mmc/assets/16916776/c0899077-7eaa-4880-807e-c33d4aca0e23)

Any idea what the problem might be?

**Comment by devbis** [comment]
It looks like an issue with z2m frontend. What z2m version do you use?

**Comment by agmorpheus** [comment]
After installing a released firmware again und restarting z2m all was good. 
I think I installed a provided beta version via https://devbis.github.io/telink-zigbee/ first.
Maybe there was the problem.
