### ISSUE TITLE
Activation not working

### ISSUE THREAD

**Issue by Flanz926** [devbis/z03mmc#166]
Hi there, I already activated and sucessfull flashed a couple of Sensors until now, but since today I cant activate them anymore. Any Ideas?
Thanks in advance. Flanz

1. Connect
2. Press "Do Actication"
3. Wait for ever.

What I tried:
Reboot, BT on/off, second thermometer

![image](https://github.com/user-attachments/assets/bb4dccf2-902e-483a-ac88-72090d247b8b)

**Comment by Misterbrot110** [comment]
same issue here, activation is not possible.

**Comment by devbis** [comment]
NB: Version: 2.1.1_0159 is temporarily not supported

If OTA flasher displays this error, the only possible way to write a custom firmware (Zigbee or custom BLE) is to use USB-UART method. To get more info, please visit https://github.com/atc1441/ATC_MiThermometer/issues/298
