### ISSUE TITLE
Slow down the internal timer

### ISSUE THREAD

**Issue by Nab0y** [devbis/z03mmc#21]
I suggest slowing down the internal timer by a factor of six. Personally, it won't make much of a difference for me whether the screen refreshes every 10 seconds or every minute. I don't experience sharp temperature fluctuations, and as a short practice has shown, the sensors don't react that quickly either. The benefits of this approach are much greater: fewer sensor queries, fewer value calculations, screen updates, and, as a result, reduced energy consumption.

I've assembled a test version for myself, and while I only have limited statistics for half a day, the battery consumption graph already looks more optimistic than it did before the changes.

Предлагаю замедлить внутренний таймер в шесть раз. Лично для меня не большая разница будет экран обновляться раз в 10 секунд или раз в минуту, таких резких перепадов температуры у меня нет, да и как показала недолгая практика сами датчики так быстро не реагируют. А пользы от такого решения намного больше, меньше опросов датчиков, меньше расчетов значений, обновлений экрана, как следствие меньше потребление энергии.
Я собрал себе тестовую версию, статистики пока мало всего пол суток, но график потребления батареи уже выглядит более оптимистично, чем было до изменений. 
![image](https://github.com/devbis/z03mmc/assets/13904687/06b788e1-bd54-4d24-ad4f-b960605584a8)
![image](https://github.com/devbis/z03mmc/assets/13904687/df26948b-a031-4497-9ada-b5f566fe6cc9)

My report settings are as follows
![image](https://github.com/devbis/z03mmc/assets/13904687/702773cb-7b25-43ef-b86e-1bf174d55b4e)

**Comment by pvvx** [comment]
10 секунд иногда уже много, для возможности удерживать температуру с гистерезисом в 0.1С, а также для любых PID регуляторов.

**Comment by Nab0y** [comment]
@devbis After the update 1.0.4, energy consumption has been normalized, and I think we can close this task as unnecessary.
