### ISSUE TITLE
Humidity sensor not working   Firmware version  1.0.3

### ISSUE THREAD

**Issue by KleinerSource** [devbis/z03mmc#26]
![image](https://github.com/devbis/z03mmc/assets/920875/d3c494cd-15b8-439e-946c-c492193b90cf)
The LCD screen displays a humidity of 0

**Comment by Mostalk** [comment]
Сonfirm. I have two sensors. Both updated to 1.0.3.
One is fine, the other also has a problem with humidity
![image](https://github.com/devbis/z03mmc/assets/9198186/ee479d2b-74f6-411d-aeff-21d0cf69b384)

**Comment by SergeyKa2021** [comment]
The same problem. HW B1.4.

**Comment by devbis** [comment]
Please, check version 1.0.4, readings conversion is fixed

**Comment by Mostalk** [comment]
Thanks. Now everything works!

```
{
    "battery": 74.5,
    "humidity": 59.7,
    "last_seen": "2023-10-27T08:37:48.151Z",
    "linkquality": 112,
    "temperature": 20.37,
    "update": {
        "installed_version": 268709889,
        "latest_version": 268709889,
        "state": "idle"
    },
    "voltage": 2700,
    "update_available": null
}
```
