### ISSUE TITLE
B1.5 Hardware LCD Support

### ISSUE THREAD

**Issue by nezg** [devbis/z03mmc#3]
Thank you for this project, good job!

I have a 1.5 hardware version, everything works fine except the screen. Is it possible to make support for version 1.5? Write if you need any help.

And it would be cool if they showed the time, as in ATC firmware.

**Comment by devbis** [comment]
[z03mmc.zip](https://github.com/devbis/z03mmc/files/12916780/z03mmc.zip)

Can you please try out this firmware to check if display works?

**Comment by devbis** [comment]
Fixed in version [1.0.1](https://github.com/devbis/z03mmc/releases/tag/1.0.1)

**Comment by nezg** [comment]
Thanks, the screen is working. 
But in release 1.0.1 there is an artifact on the screen in the upper right character.
According to observations, it appears before the temperature change.
It's hard to catch, but there are on both sensors.
![viber image](https://github.com/devbis/z03mmc/assets/113188518/13d4ef04-de35-43e5-9b33-5b7a2ef7ee7a)
