### ISSUE TITLE
How to do OTA?

### ISSUE THREAD

**Issue by kubert96** [devbis/z03mmc#32]
I have aded and flashed device on 1.0.4 and now 1.0.5 is out. 
How to do ota? 
Bluetooth is not working as expected. 
And in zigbee2mqtt OTA doesnt register any update. 

installed_version: 268709889
latest_version: 268709889

 Update available: false

Firmware version: 3001-1004
<img width="1313" alt="Screenshot 2023-10-30 at 23 28 00" src="https://github.com/devbis/z03mmc/assets/68554211/ef153ceb-bab5-4930-ab68-3f3dca129a6f">
<img width="1641" alt="Screenshot 2023-10-30 at 23 27 46" src="https://github.com/devbis/z03mmc/assets/68554211/6f1fa4a5-cb58-4446-9ad4-acf42d0e4d17">

Thanks :)

**Comment by Mostalk** [comment]
Use this in "OTA index override"

```
[
     {
         "fileVersion": 268775425,
         "manufacturerCode": 4417,
         "imageType": 515,
         "url": "https://github.com/devbis/z03mmc/releases/download/1.0.5/1141-0203-10053001-z03mmc.zigbee"
     }
]
```

**Comment by kubert96** [comment]
error 2023-10-31 07:19:44Update of 'Office Aquara Temp' failed (Device didn't respond to OTA request)

**Comment by kubert96** [comment]
info 2023-10-31 08:42:28MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"Office Aquara Temp"},"error":"Update of 'Office Aquara Temp' failed (Device didn't respond to OTA request)","status":"error","transaction":"6594s-2"}'
error 2023-10-31 08:42:28Update of 'Office Aquara Temp' failed (Device didn't respond to OTA request)

**Comment by Mostalk** [comment]
@kubert96 
Hmm, it worked for me. With such an error, it helped me to reset the battery.

In any case, you can just wait until @devbis updates the OTA index repository.

**Comment by devbis** [comment]
https://github.com/Koenkk/zigbee-OTA/pull/386

PR to track

**Comment by kubert96** [comment]
info 2023-10-31 09:20:02MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"Office Aquara Temp"},"error":"Update of 'Office Aquara Temp' failed (Unexpected string in JSON at position 160056)","status":"error","transaction":"gbkbn-2"}'

New Error... :D

**Comment by Nab0y** [comment]
One of my eight sensors also refuses to update via OTA, but it reports a slightly different error. 
`Info 2023-10-31 14:12:00MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"Температура влажность кухня"},"error":"Update of 'Температура влажность кухня' failed (Timeout: device did not request any image blocks)","status":"error","transaction":"j9w29-1"}'
Error 2023-10-31 14:12:00Update of 'Температура влажность кухня' failed (Timeout: device did not request any image blocks)`
I suspect that it's because this sensor is the only one currently connected not directly to the coordinator but to the nearest router, and the issue might not be with the sensor itself but with the router, which seems to be refusing to pass on the update through itself. Well, that's my theory, at least.
![image](https://github.com/devbis/z03mmc/assets/13904687/8620eb04-b05e-4d46-a925-a8d8c743bb0f)

**Comment by kubert96** [comment]
Mine is directly conected to Cordinator. 

![Screenshot 2023-10-31 at 12 26 07](https://github.com/devbis/z03mmc/assets/68554211/8b7bd622-e30f-4e90-b8e7-28aec6211193)

**Comment by devbis** [comment]
> device did not request any image blocks
usually means that OTA image and fw version is the same. But if it is not, you may replug the battery and push OTA again

**Comment by Nab0y** [comment]
> Mine is directly conected to Cordinator.
> 
> ![Screenshot 2023-10-31 at 12 26 07](https://user-images.githubusercontent.com/68554211/279358777-8b7bd622-e30f-4e90-b8e7-28aec6211193.png)

Yes, it's not my case. You can try to forcefully make the sensor take the firmware from a local folder.
![image](https://github.com/devbis/z03mmc/assets/13904687/885e7eba-e4e9-4290-85d1-ef2261dedef3)
![image](https://github.com/devbis/z03mmc/assets/13904687/d546d8dc-83dc-46d0-b2e3-eaa7b48e2e5a)
After that, you'll need to restart Z2M since the configuration file has been modified. And once you're done, don't forget to revert everything back to its original state.

**Comment by Nab0y** [comment]
> > device did not request any image blocks
> 
> usually means that OTA image and fw version is the same. But if it is not, you may replug the battery and push OTA again

That's what I intend to do, but it will take me a few hours to physically reach the sensor :)

**Comment by kubert96** [comment]
This is after i restarted sensor: 
MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"Office Aquara Temp"},"error":"Update of 'Office Aquara Temp' failed (localIndex.concat(...).map is not a function)","status":"error","transaction":"pfbx3-3"}'

**Comment by kubert96** [comment]
OK :D 

info 2023-10-31 13:05:42MQTT publish: topic 'zigbee2mqtt/Office Aquara Temp', payload '{"battery":90,"humidity":62.36,"linkquality":102,"temperature":24.06,"update":{"installed_version":268709889,"latest_version":268775425,"progress":0,"state":"updating"},"update_available":false,"voltage":2900}'

Finaly working. With Local File. :) 

@Nab0y thank you :)

**Comment by adorobis** [comment]
> usually means that OTA image and fw version is the same. But if it is not, you may replug the battery and push OTA again

For me some devices don't show correct fw version information in z2m (not in HA) although they were updated successfully. I have such case for 1 of 3 of the temp sensors but also some other devices (e.g. xiaomi wall switches). Re-inserting batteries and clicking "check for updates" does not help. Example below. Anyway it seems a z2m issue as it is not limited to those sensors.
![image](https://github.com/devbis/z03mmc/assets/19752098/ee6091a0-f645-4722-b067-2783a448374b)

**Comment by devbis** [comment]
@adorobis You can read newer values for devices using dev console for a device
<img width="1292" alt="Screenshot 2023-10-31 at 18 06 53" src="https://github.com/devbis/z03mmc/assets/12081127/69cecb70-9f62-45ba-b957-c32437b52c63">

**Comment by adorobis** [comment]
I get either timeout or nothing changes. Still shows the old version in z2m.

**Comment by fraddygil** [comment]
Hey Guys , Is there any way to go back to the original firmware or any ATC firmware?

**Comment by Nab0y** [comment]
> Hey Guys , Is there any way to go back to the original firmware or any ATC firmware? Using OTA or another option?

https://github.com/devbis/z03mmc#flashing-firmware-with-usb-to-uart

**Comment by shirou93** [comment]
> > Mine is directly conected to Cordinator.
> > ![Screenshot 2023-10-31 at 12 26 07](https://user-images.githubusercontent.com/68554211/279358777-8b7bd622-e30f-4e90-b8e7-28aec6211193.png)
> 
> Yes, it's not my case. You can try to forcefully make the sensor take the firmware from a local folder. ![image](https://user-images.githubusercontent.com/13904687/279361809-885e7eba-e4e9-4290-85d1-ef2261dedef3.png) ![image](https://user-images.githubusercontent.com/13904687/279364001-d0541dff-94fe-419c-a93e-6b775a7e3ce9.png)
> 
> After that, you'll need to restart Z2M since the configuration file has been modified. And once you're done, don't forget to revert everything back to its original state.

Thanks Your solution working :)

**Comment by beeline09** [comment]
> [Koenkk/zigbee-OTA#386](https://github.com/Koenkk/zigbee-OTA/pull/386)
> 
> PR to track

Надо бы это добавить в инструкцию по откату назад. Долго ходил вокруг, да около, пока не наткнулся на это.

**Comment by Psytoshgen** [comment]
> > [Koenkk/zigbee-OTA#386](https://github.com/Koenkk/zigbee-OTA/pull/386)
> > PR to track
> 
> Надо бы это добавить в инструкцию по откату назад. Долго ходил вокруг, да около, пока не наткнулся на это.

тут все просто.... останавливаем z2m залазим в файл state.json и в latest version пишем (например файл на который хотим называется 1141-0208-01143001-ZMHOC401N) в последней версии прописываем 01143001 и после запуска z2m видим приглашение обновиться.... а вот как обновиться с альтернативной, еще не придумал...

**Comment by beeline09** [comment]
> > > [Koenkk/zigbee-OTA#386](https://github.com/Koenkk/zigbee-OTA/pull/386)
> > > PR to track
> > 
> > 
> > Надо бы это добавить в инструкцию по откату назад. Долго ходил вокруг, да около, пока не наткнулся на это.
> 
> тут все просто.... останавливаем z2m залазим в файл state.json и в latest version пишем (например файл на который хотим называется 1141-0208-01143001-ZMHOC401N) в последней версии прописываем 01143001 и после запуска z2m видим приглашение обновиться.... а вот как обновиться с альтернативной, еще не придумал...

Да, спасибо, я именно так и сделал) с альтернативной имеется ввиду не вашей?
