### ISSUE TITLE
Zigbee2MQTT Reporting time

### ISSUE THREAD

**Issue by nobet78** [devbis/z03mmc#35]
Why is the set time in the Zigbee2MQTT Reporting panel not taken into account. I set it to 180 and the actual reporting time is random up to 7 minutes. Has anyone encountered this?

**Comment by fryc88** [comment]
Mine doesn't seem to be accepting reporting time changes, temp, humidity and battery are reporting after bang on every 5 minutes, which is draining battery quite a lot i guess - got 78% left from brand new battery, all flashed at saturday so it's 5th day of using it today. I only flashed one of my whole lot of these termometers to see battery drain, but that doesn't look well. With stock BT firmware they lasted 9-12 months each, with custom ATC they were about 4-5 months...
I've got 1.0.4 firmware now, trying to do OTA to 1.0.5 but they don't mention any battery/reporting changes

**Comment by wimpie007** [comment]
my 2 devices report every minute spot on.
killing battery.😥

**Comment by pvvx** [comment]
The current version 1.0.5 after "bind clasters" passes all values every 10 seconds.
Changing the parameters of the "report" (times) does not work.

**Comment by wimpie007** [comment]
mmm, how can we lower the report frequency?
only with an other firmware?

**Comment by pvvx** [comment]
Do not “link clusters” 0x402, 0x405,.., but request these attributes using any timer.

**Comment by wimpie007** [comment]
zigbee thermometers only transmit when values are changed, and never very fast like 10 seconds.
I dont need to have such a detailed reports. once every x minutes is fine with me.
the reason to use zigbee? range is superieur because i have zigbee devices everywhere. (BLE requires extra devices...)

**Comment by pvvx** [comment]
To change the display, it is also required to wake up all the chips in the thermometer, which does not allow for low consumption in the Zigbee version.

**Comment by devbis** [comment]
Fixed applying of received reporting values in https://github.com/devbis/z03mmc/releases/tag/1.0.6.
