### ISSUE TITLE
Rollback guide to bluetooth

### ISSUE THREAD

**Issue by raknam** [devbis/z03mmc#39]
Is it possible to get a guide to rollback to the bluetooth firmware? Maybe via Zigbee OTA?

**Comment by IvanGavrilenko** [comment]
You can get original or modified Bluetooth firmware [here](https://github.com/pvvx/ATC_MiThermometer#firmware-binaries) and flash it via USB to UART

**Comment by devbis** [comment]
Added a paragraph about reverting to BLE over UART

**Comment by pvvx** [comment]
[Zigbee OTA firmware files for recovery in BLE](https://github.com/pvvx/ATC_MiThermometer/tree/master/zigbee_ota)

**Comment by devbis** [comment]
@pvvx Are these firmwares tested? Can I recomment them in the project readme?

**Comment by pvvx** [comment]
This is a typical firmware with headers for Zigbee OTA.

**Comment by devbis** [comment]
I made such experiments it they failed in 50%. What would happen if BLE firmware is written to address 0x40000?

**Comment by pvvx** [comment]
Fixed and tested.

**Comment by raknam** [comment]
Thank you !! :)
