### ISSUE TITLE
Support Fahrenheit degrees on display

### ISSUE THREAD

**Issue by devbis** [devbis/z03mmc#4]

**Comment by khayamgondal** [comment]
Hi, do you have a plan to work on this? Great initiative btw :)

**Comment by devbis** [comment]
Yes, just finished it. You can try firmware from a branch build https://github.com/devbis/z03mmc/actions/runs/6756695293
Keep in mind that you should use [updated convertor for z2m ](https://github.com/devbis/z03mmc/blob/fahrenheit/converters/lywsd03mmc.js)

Will merge it later

**Comment by devbis** [comment]
Added in https://github.com/devbis/z03mmc/releases/tag/1.0.6

**Comment by jds11111** [comment]
Does anyone know if this will show up for OTA update on Z2M, or do we need to do it manually?

Great work, devbis.

**Comment by devbis** [comment]
@jds11111 You may track the PR for updates in z2m https://github.com/Koenkk/zigbee-OTA/pull/395

**Comment by jds11111** [comment]
I am feeling stupid: I don't see how to set it.

**Comment by devbis** [comment]
You have 4 options
1.  Add custom convertor from this repo
2. Install dev version of z2m, the updated converter is merged there
3. Write value 1 to thertmostatUIConfig/displayMode cluster manually using dev console
4. Wait until next release of z2m, the toggle will be there

**Comment by jds11111** [comment]
Ahh. Thanks. For me it was hvacUserInterfaceCfg/TmpDisplayMode to 1 that did the trick.
