### ISSUE TITLE
Zigbee2MQTT Sonoff dongle-e v2 не работает

### ISSUE THREAD

**Issue by malehovich** [devbis/z03mmc#44]
После смены на Sonoff zigbee dongle-E v2 "product":8,"revision":"6.10.3.0 build 297"},"type":"EZSP v8" на последней прошивке устройство не регистрируется. По логам оно как будто вообще ничего не шлет. На dongle-P все работает. Прошивал через OTA на dongle-P. Рядом датчик Xiaomi на dongle-E регистрируется без проблем. Батарейку вынимал. Контакты GND и reset замыкал.

**Comment by devbis** [comment]
Какая версия прошивки?

**Comment by malehovich** [comment]
Версия от 30 октября. 1.0.5

**Comment by devbis** [comment]
Duplicate of https://github.com/devbis/z03mmc/issues/12
