### ISSUE TITLE
Fix sleeping during reconnection mode

### ISSUE THREAD

**Issue by devbis** [devbis/z03mmc#46]
In case of unavailable coordinator the sensor tries to reconnect in a loop. It drains battery.
Make it sleep for minutes after several attempts.

**Comment by pvvx** [comment]
https://github.com/devbis/tl_zigbee_sdk/blob/3.6.8.5/zigbee/common/includes/zb_config.h#L89
https://github.com/devbis/tl_zigbee_sdk/blob/3.6.8.5/zigbee/zdo/zdo_api.h#L97

**Comment by devbis** [comment]
Fixed in https://github.com/devbis/z03mmc/releases/tag/1.0.6

**Comment by pvvx** [comment]
> Make it sleep for minutes after several attempts.

Это не поможет.
Один цикл rejoin и пару процентов CR2032 уже нет. Т.е. при настройках в SDK батарейки хватит на несколько минут.
Аналогичная ситуация и при join.
