### ISSUE TITLE
Поддержка других систем умного дома

### ISSUE THREAD

**Issue by AndreyGrech** [devbis/z03mmc#59]
Есть планы по добавлению поддержки других платформ, куда можно добавить датчик напрямую, таких как tuya или ewelink. И можно ли сейчас туда добавить датчик

**Comment by devbis** [comment]
Таких планов сейчас нет, т.к. у меня нет соответствующих шлюзов. Если кто-то проверит решение, например замена модели на ту, что известна шлюзу, то я добавлю соответствующие изменения или сборки отдельного варианта прошивки.

**Comment by AndreyGrech** [comment]
Спасибо автору klu16 он показал что с tuya будет работать
