### ISSUE TITLE
Temperature calibration

### ISSUE THREAD

**Issue by adamlc** [devbis/z03mmc#62]
Just wanted to say thanks for your great work, got 9 devices moved over to zigbee and its been very reliable.

One of my devices is quite a bit out for humidity, about +6%.

I can change the calibration in z2m, which gets reflected over zigbee, but the display still shows the wrong value. Not sure if this is expected behaviour? As all my other zigbee sensors don't have displays.

Thanks!

**Comment by devbis** [comment]
I suppose calibration in z2m just calibrates received values. ZCL default clusters don't allow out-of-box configuring for calibrated values in the sensor.

**Comment by adamlc** [comment]
Ahh that makes sense. Thanks for the clarification!
