### ISSUE TITLE
zigbee2mqtt version 1.33.1-1 isn't working

### ISSUE THREAD

**Issue by Harwesta** [devbis/z03mmc#7]
zigbee2mqtt  ver. 1.33.1-1 addon in HA version not recognized this sensor after flash zigbee FW.

**Comment by devbis** [comment]
Use this converter for zigbee2mqtt https://github.com/devbis/z03mmc/blob/master/converters/lywsd03mmc.js

**Comment by xxddff** [comment]
I'm also using Sonoff zigbee dongle -E v2
I would like to know if there is a way to restore to the official Bluetooth firmware or pvvx custom firmware? (I want to go through OTA as much as possible instead of opening the device)

**Comment by Harwesta** [comment]
> I want to go through OTA as much as possible instead of opening the device.
No chance.
Go to the light side of the force: solder the wires and flash them back

**Comment by xxddff** [comment]
> > I want to go through OTA as much as possible instead of opening the device.
> 
> No chance.
> 
> Go to the light side of the force: solder the wires and flash them back
> 
> 
> 
> 

Thank you for your quick reply. I will try to open the device and flash it. I hope you can solve the EZSP coordinator issue soon. I prefer to use the zigbee network that I already have at home for these sensors, rather than bluetooth. Appreciate your excellent work :D

**Comment by devbis** [comment]
[revert-to-ble-lywsd03mmc.zigbee.zip](https://github.com/devbis/z03mmc/files/13054913/revert-to-ble-lywsd03mmc.zigbee.zip)

I was lucky to use this OTA image to revert to BLE firmware again, but the other time it got bricked. You may use it but no warranty at all. It is just BLE firmware with zigbee ota header
