### ISSUE TITLE
LYWSD03MMC - HW: B2.0

### ISSUE THREAD

**Issue by GiacomoFilzi** [devbis/z03mmc#72]
Hi everyone,
really appricate the work you guys are doing. Awesome.
I tried the "over air" method for a LYWSD03MMC B2.0.
I flashed the ATC_ota_400000 first, update successful.
After reconnecting I flashed the newest z03mmc.bin (version 1.0.6) - update was also successful.
However, now I can't detect it via bluetooth nor via home assist, which makes me wonder: Is the B2.0 not supported? If so, are there plans to roll out a version B2.0 support in the future? Or did I do something wrong.

Thanks guys,
Giacomo Filzi

**Comment by devbis** [comment]
B2.0 is supported. What zigbee coordinator chip do you use?

**Comment by GiacomoFilzi** [comment]
So it's normal that I can't connect again to the Web-Flasher after that process? I'm using a Conbee 2 and tried connecting over Deconz.

**Comment by devbis** [comment]
Web flasher works over bluetooth and this firmware uses zigbee to communicate with the device.
Unfortunately, I'm not familiar with deconz/conbee, can't tell the details

**Comment by GiacomoFilzi** [comment]
ok, after some research I found out a couple of things:
- deconz does currently not support the sensor, however its requested by the community: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7327
- zigbee2mqtt would work, but can't run parallel to deconz - so I would need to completely switch my devices over..

Just wanted to share - I guess the issue is solved - thanks.

**Comment by GiacomoFilzi** [comment]
solved.
