### ISSUE TITLE
Problems building the firmware (CMAKE)

### ISSUE THREAD

**Issue by breaver** [devbis/z03mmc#73]
When executing this command, 

`cmake -B build -DSDK_PREFIX=$(pwd)/../tl_zigbee_sdk -DTOOLCHAIN_PREFIX=$(pwd)/../tc32 -DMANUFACTURER_CODE=0x1141`

i receive below error:

```
D:\Downloads\z03mmc>cmake -B build -DSDK_PREFIX=$(pwd)/../tl_zigbee_sdk -DTOOLCHAIN_PREFIX=$(pwd)/../tc32 -DMANUFACTURER_CODE=0x1141
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:11 (PROJECT):
  Running

   'nmake' '-?'

  failed with:

   no such file or directory


-- Configuring incomplete, errors occurred!
```

I am running on Windows. Any clue?

**Comment by pvvx** [comment]
This assembly is not compatible with [Telink_IoT_Studio](http://wiki.telink-semi.cn/wiki/IDE-and-Tools/Telink_IoT_Studio/).
Install the full MSYS or MinGW package... 
Or use WSL (preferred for this build).

**Comment by devbis** [comment]
@breaver I don't have x86_64 windows to check it, can you please run cmake configure with explicit specifying generator:

```sh
cmake -B build  -G "Unix Makefiles" -DSDK_PREFIX=$(pwd)/../tl_zigbee_sdk -DTOOLCHAIN_PREFIX=$(pwd)/../tc32 -DMANUFACTURER_CODE=0x1141```

or

```sh
cmake -B build  -G "MSYS Makefiles" -DSDK_PREFIX=$(pwd)/../tl_zigbee_sdk -DTOOLCHAIN_PREFIX=$(pwd)/../tc32 -DMANUFACTURER_CODE=0x1141```

**Comment by pvvx** [comment]
https://github.com/devbis/tc32.git does not contain cmake.exe, nmake.exe, make.exe, ... and other files for assembly

**Comment by devbis** [comment]
@pvvx don't mess up toolchain and build essentials

**Comment by pvvx** [comment]
There are different "build tools and foundations" on Windows - MSYS, MinGW, Visual studio, ...

**Comment by pvvx** [comment]
```
git clone https://github.com/devbis/tc32.git -b windows
```
Contains broken exe files.
Example:  https://github.com/devbis/tc32/raw/windows/tc32-elf/bin/gcc.exe

**Comment by breaver** [comment]
> @breaver I don't have x86_64 windows to check it, can you please run cmake configure with explicit specifying generator:
> 
> ```shell
> cmake -B build  -G "Unix Makefiles" -DSDK_PREFIX=$(pwd)/../tl_zigbee_sdk -DTOOLCHAIN_PREFIX=$(pwd)/../tc32 -DMANUFACTURER_CODE=0x1141
> ```
> 
> or
> 
> ```shell
> cmake -B build  -G "MSYS Makefiles" -DSDK_PREFIX=$(pwd)/../tl_zigbee_sdk -DTOOLCHAIN_PREFIX=$(pwd)/../tc32 -DMANUFACTURER_CODE=0x1141
> ```

Tried both ways. Do not work:

```
D:\Downloads\z03mmc>cmake -B build  -G "Unix Makefiles" -DSDK_PREFIX=$(pwd)/../tl_zigbee_sdk -DTOOLCHAIN_PREFIX=$(pwd)/../tc32 -DMANUFACTURER_CODE=0x1141
CMake Error: Error: generator : Unix Makefiles
Does not match the generator used previously: NMake Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.

D:\Downloads\z03mmc>cmake -B build  -G "MSYS Makefiles" -DSDK_PREFIX=$(pwd)/../tl_zigbee_sdk -DTOOLCHAIN_PREFIX=$(pwd)/../tc32 -DMANUFACTURER_CODE=0x1141
CMake Error: Error: generator : MSYS Makefiles
Does not match the generator used previously: NMake Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
```

Sorry i am not an expert on this, what i now did instead, is using the binary file which is linked in the [release ](https://github.com/devbis/z03mmc/releases)section

I guess building the binary is not necessary then ?!

**Comment by devbis** [comment]
Yes, building is not necessary, you may take a binary from the release. To build with a different generator you need to delete build folder in advance

**Comment by breaver** [comment]
Then this topic can be closed. Sorry and thanks for your help!

**Comment by devbis** [comment]
> Contains broken exe files.

toolchain for windows is synced with files from IDE setup.

**Comment by pvvx** [comment]
> toolchain for windows is synced with files from IDE setup.

But during compilation an error occurs (crash in the exe file). Telink IDE does not have nmake and many other utilities when running CMAKE scripts.

**Comment by devbis** [comment]
Use either visual studio for nmake or other generators. Cmake supports many of them

**Comment by pvvx** [comment]
I can assemble anything without any problems. I use dozens of different microcontrollers...
But according to your instructions, users will not be able to build the project in Windows.

**Comment by devbis** [comment]
So, can you suggest any solution for cmake on windows?

**Comment by pvvx** [comment]
Requires installation of MSYS or MinGW, as well as Python and git.
PATH path settings are individual. There are many MSYS MinGW packages...

In the end, it’s better to use something ready-made. For example, 'Telink IoT Studio' and throw away СMAKE - Significantly simplifies the assembly option and reduces the time for this action..
