### ISSUE TITLE
Any plan to convert MCCGQ02HL to Zigbee?

### ISSUE THREAD

**Issue by onurunaldi** [devbis/z03mmc#77]
Hi,
Thank you for your great work on Mi thermometer. I am using it with joy. Do you have any plan to create a zigbee firmware for Mi door/window sensor 2 or is it even possible to make such work?

Thanks in advance.

**Comment by devbis** [comment]
Hi! Thanks for using this firmware. As for MCCGQ02HL, I don't have any of those, but according to MAC it has a different manufacturer, so it is not planned at the moment. And it could even not be possible, it depends on the SDK provided by manufacturer.
