### ISSUE TITLE
Enable Fahrenheit in ZHA

### ISSUE THREAD

**Issue by scarolan** [devbis/z03mmc#78]
I'm not seeing a cluster for toggling between C and F.

I'm running the latest 1.0.6 firmware.  Is it possible to change the display to Fahrenheit with ZHA?

**Comment by devbis** [comment]
While I'm figuring out why it is not exposed to UI, you may try ZHA toolkit https://github.com/mdeweerd/zha-toolkit#attr_write-writeread-an-attribute-value and write 1 (Fahrenheit) to 
- endpoint 1
- cluster 0x0204
- attribute 0x0000
- attr_type 0x30 
- value 1

**Comment by scarolan** [comment]
Thanks @devbis - I tried the workaround but ZHA toolkit throws an error

![image](https://github.com/devbis/z03mmc/assets/403332/a94d721e-6169-45ed-8ac9-6d98d9862ff5)

Also am not seeing a 0x0204 cluster - there is an 0x0402 though?

![image](https://github.com/devbis/z03mmc/assets/403332/401a1073-4234-4b5d-b2db-2a22d2706640)

**Comment by devbis** [comment]
You should use `0x0204 Thermostat User Interface Configuration`, which is absent in the list.
If you're sure you're using 1.0.6, it could be a filter on ZHA side. 
Though, it is mentioned in zigpy: https://github.com/zigpy/zigpy/blob/dev/zigpy/zcl/clusters/hvac.py#L658-L670

**Comment by pvvx** [comment]
https://github.com/mdeweerd/zha-toolkit/blob/main/custom_components/zha_toolkit/utils.py#L444
Log:
_Exception: No endpoint None and no cluster 0x0204 for 'a4:c1:38:0b:5e:ed:c6:97'_

**Comment by scarolan** [comment]
No worries, I can wait.  The degrees on the display is not mission critical for my use case.

**Comment by devbis** [comment]
@scarolan At last I was able to check switching to degrees Fahrenheit in ZHA. Unfortunately, raw zha just ignores cluster 0x0204, so I used zha-toolkit. (ieee - any entity from the device, battery, temperature, humidity, doesn't matter)

```yaml
service: zha_toolkit.attr_write
data:
  ieee: sensor.xiaomi_lywsd03mmc_battery
  cluster: 516
  attribute: 0
  attr_val: "1"
```

I used developer mode to run services. Can you please try it?


<img width="1364" alt="Screenshot 2023-12-28 at 02 03 43" src="https://github.com/devbis/z03mmc/assets/12081127/4baae271-d0dd-4042-bd4e-e43a38e574f5">

**Comment by pvvx** [comment]
> Unfortunately, raw zha just ignores cluster 0x0204, so I used zha-toolkit. 

The cluster 0x0204 is not declared in the lists in the firmware.
https://github.com/pvvx/ZigbeeTLc/issues/28

**Comment by scarolan** [comment]
Nice!  What should I put for "Target Cluster"?  I tried 516 like the example but didn't get a result.

**Comment by scarolan** [comment]
I'm good with BLE for now, will keep my single Celsius Zigbee device for quick reference ;-)

**Comment by devbis** [comment]
@scarolan The latest firmware supports switching via 1 sec pressing on reset-gnd contacts. 
And switching via cluster attribute is also fixed.

**Comment by scarolan** [comment]
Nice work, @devbis!
