### ISSUE TITLE
Thread / Matter Support?

### ISSUE THREAD

**Issue by the-kenny** [devbis/z03mmc#79]
Would you consider adding Thread (and on top of that, Matter) support in the future? Is that even feasible, given the hardware?

**Comment by devbis** [comment]
According to this table http://wiki.telink-semi.cn/wiki/index.html only the latest chips 92xx support Matter/Thread. So I believe Telink would not backport their SDK for 825x chips.

**Comment by the-kenny** [comment]
That's too bad. Thanks for the fast response!
