### ISSUE TITLE
LYWSD02MMC

### ISSUE THREAD

**Issue by sweethome29** [devbis/z03mmc#83]
Приветствую) а для LYWSD02MMC не планируется прошивки? Возможно ли вообще такое повторить на нем?

**Comment by pvvx** [comment]
https://pvvx.github.io/LYWSD02/
Refer to those that work with Renesas chips: https://www.renesas.com/us/en/products/wireless-connectivity/bluetooth-low-energy/da14585-smartbond-bluetooth-50-soc-audio-interface
