### ISSUE TITLE
Precision settings

### ISSUE THREAD

**Issue by Arytmia** [devbis/z03mmc#85]
Hi,
Just converted to zigbee and working great.
My problem is, that temperature offset is huge (around 6°).
I did calibration in zigbe2mqtt, but values on display are still the same.
Any chance to calibrate values on screen?

**Comment by pvvx** [comment]
The original Xiaomi LYWSD03MMC has an increased humidity of 5%. The temperature is usually without correction.

**Comment by Arytmia** [comment]
> The original Xiaomi LYWSD03MMC has an increased humidity of 5%. The temperature is usually without correction.
> 
> https://forum.arduino.cc/t/compare-different-i2c-temperature-and-humidity-sensors-sht2x-sht3x-sht85/599609/23

I respect that and accept it. Unfortunately, mine got huge plus corrections when changing the software. I replaced the battery with a new one because the flashing process killed the previous one, but the high values remained. Therefore, I would like to be able to make a correction for the display, since it is the only BLE device I use and I don't want to specifically create a gate on the ESP for it.

**Comment by pvvx** [comment]
When [my firmware version](https://github.com/pvvx/ZigbeeTLc) comes out of beta testing, I will try to make the necessary adjustments...

**Comment by yangrusen** [comment]
> The original Xiaomi LYWSD03MMC has an increased humidity of 5%. The temperature is usually without correction.
> 
> https://forum.arduino.cc/t/compare-different-i2c-temperature-and-humidity-sensors-sht2x-sht3x-sht85/599609/23

May I know if you have added that offset in zigbee firmware?

**Comment by pvvx** [comment]
https://github.com/pvvx/ZigbeeTLc?tab=readme-ov-file#setting-offsets-for-temperature-and-humidity

**Comment by devbis** [comment]
@Arytmia starting z2m 1.35.3 calibration settings are in the device converter. For ZHA and other controllers, clusters/attibutes are described in the readme.
