### ISSUE TITLE
请问过度固件的PIN码是什么

### ISSUE THREAD

**Issue by astangcong** [devbis/z03mmc#92]
我刷了过度固件以后不小心把蓝牙从电脑的已连接设备删除后无法连接了，每次连接的时候电脑/手机都会提示让输入配对码（pin），导致现在没办法连接，也就没办法进行第二步刷机了

**Comment by devbis** [comment]
All firmwares don't have pin codes. Maybe you need to reboot or use any code, like 0000.

**Comment by astangcong** [comment]
> All firmwares don't have pin codes. Maybe you need to reboot or use any code, like 0000.

I've tried 0000 or 1234，even anyother pin codes，but all failed...

**Comment by pvvx** [comment]
All alternative BLE firmwares have the ability to set a “pin code”.
If you have forgotten your PIN code, then the only thing that will help is to completely erase the entire Flash programmer over the wire and write a new firmware.
